# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/amir/Geant4/geant4-v11.1.2/sim/Gamma_on_lH2-main_new_physics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/amir/Geant4/geant4-v11.1.2/sim/Gamma_on_lH2-main_new_physics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amir/Geant4/geant4-v11.1.2/sim/Gamma_on_lH2-main_new_physics/CMakeFiles /home/amir/Geant4/geant4-v11.1.2/sim/Gamma_on_lH2-main_new_physics//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amir/Geant4/geant4-v11.1.2/sim/Gamma_on_lH2-main_new_physics/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sim

# Build rule for target.
sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sim
.PHONY : sim

# fast build rule for target.
sim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/build
.PHONY : sim/fast

#=============================================================================
# Target rules for targets named simulation

# Build rule for target.
simulation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simulation
.PHONY : simulation

# fast build rule for target.
simulation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/build
.PHONY : simulation/fast

ElectromagneticPhysics.o: ElectromagneticPhysics.cc.o
.PHONY : ElectromagneticPhysics.o

# target to build an object file
ElectromagneticPhysics.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/ElectromagneticPhysics.cc.o
.PHONY : ElectromagneticPhysics.cc.o

ElectromagneticPhysics.i: ElectromagneticPhysics.cc.i
.PHONY : ElectromagneticPhysics.i

# target to preprocess a source file
ElectromagneticPhysics.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/ElectromagneticPhysics.cc.i
.PHONY : ElectromagneticPhysics.cc.i

ElectromagneticPhysics.s: ElectromagneticPhysics.cc.s
.PHONY : ElectromagneticPhysics.s

# target to generate assembly for a file
ElectromagneticPhysics.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/ElectromagneticPhysics.cc.s
.PHONY : ElectromagneticPhysics.cc.s

GammaNuclearPhysics.o: GammaNuclearPhysics.cc.o
.PHONY : GammaNuclearPhysics.o

# target to build an object file
GammaNuclearPhysics.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/GammaNuclearPhysics.cc.o
.PHONY : GammaNuclearPhysics.cc.o

GammaNuclearPhysics.i: GammaNuclearPhysics.cc.i
.PHONY : GammaNuclearPhysics.i

# target to preprocess a source file
GammaNuclearPhysics.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/GammaNuclearPhysics.cc.i
.PHONY : GammaNuclearPhysics.cc.i

GammaNuclearPhysics.s: GammaNuclearPhysics.cc.s
.PHONY : GammaNuclearPhysics.s

# target to generate assembly for a file
GammaNuclearPhysics.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/GammaNuclearPhysics.cc.s
.PHONY : GammaNuclearPhysics.cc.s

HadronElasticPhysicsHP.o: HadronElasticPhysicsHP.cc.o
.PHONY : HadronElasticPhysicsHP.o

# target to build an object file
HadronElasticPhysicsHP.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/HadronElasticPhysicsHP.cc.o
.PHONY : HadronElasticPhysicsHP.cc.o

HadronElasticPhysicsHP.i: HadronElasticPhysicsHP.cc.i
.PHONY : HadronElasticPhysicsHP.i

# target to preprocess a source file
HadronElasticPhysicsHP.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/HadronElasticPhysicsHP.cc.i
.PHONY : HadronElasticPhysicsHP.cc.i

HadronElasticPhysicsHP.s: HadronElasticPhysicsHP.cc.s
.PHONY : HadronElasticPhysicsHP.s

# target to generate assembly for a file
HadronElasticPhysicsHP.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/HadronElasticPhysicsHP.cc.s
.PHONY : HadronElasticPhysicsHP.cc.s

MyG4StepLimiterPhysics.o: MyG4StepLimiterPhysics.cc.o
.PHONY : MyG4StepLimiterPhysics.o

# target to build an object file
MyG4StepLimiterPhysics.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/MyG4StepLimiterPhysics.cc.o
.PHONY : MyG4StepLimiterPhysics.cc.o

MyG4StepLimiterPhysics.i: MyG4StepLimiterPhysics.cc.i
.PHONY : MyG4StepLimiterPhysics.i

# target to preprocess a source file
MyG4StepLimiterPhysics.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/MyG4StepLimiterPhysics.cc.i
.PHONY : MyG4StepLimiterPhysics.cc.i

MyG4StepLimiterPhysics.s: MyG4StepLimiterPhysics.cc.s
.PHONY : MyG4StepLimiterPhysics.s

# target to generate assembly for a file
MyG4StepLimiterPhysics.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/MyG4StepLimiterPhysics.cc.s
.PHONY : MyG4StepLimiterPhysics.cc.s

PhysicsList.o: PhysicsList.cc.o
.PHONY : PhysicsList.o

# target to build an object file
PhysicsList.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/PhysicsList.cc.o
.PHONY : PhysicsList.cc.o

PhysicsList.i: PhysicsList.cc.i
.PHONY : PhysicsList.i

# target to preprocess a source file
PhysicsList.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/PhysicsList.cc.i
.PHONY : PhysicsList.cc.i

PhysicsList.s: PhysicsList.cc.s
.PHONY : PhysicsList.s

# target to generate assembly for a file
PhysicsList.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/PhysicsList.cc.s
.PHONY : PhysicsList.cc.s

RadioactiveDecayPhysics.o: RadioactiveDecayPhysics.cc.o
.PHONY : RadioactiveDecayPhysics.o

# target to build an object file
RadioactiveDecayPhysics.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/RadioactiveDecayPhysics.cc.o
.PHONY : RadioactiveDecayPhysics.cc.o

RadioactiveDecayPhysics.i: RadioactiveDecayPhysics.cc.i
.PHONY : RadioactiveDecayPhysics.i

# target to preprocess a source file
RadioactiveDecayPhysics.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/RadioactiveDecayPhysics.cc.i
.PHONY : RadioactiveDecayPhysics.cc.i

RadioactiveDecayPhysics.s: RadioactiveDecayPhysics.cc.s
.PHONY : RadioactiveDecayPhysics.s

# target to generate assembly for a file
RadioactiveDecayPhysics.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/RadioactiveDecayPhysics.cc.s
.PHONY : RadioactiveDecayPhysics.cc.s

action.o: action.cc.o
.PHONY : action.o

# target to build an object file
action.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/action.cc.o
.PHONY : action.cc.o

action.i: action.cc.i
.PHONY : action.i

# target to preprocess a source file
action.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/action.cc.i
.PHONY : action.cc.i

action.s: action.cc.s
.PHONY : action.s

# target to generate assembly for a file
action.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/action.cc.s
.PHONY : action.cc.s

construction.o: construction.cc.o
.PHONY : construction.o

# target to build an object file
construction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/construction.cc.o
.PHONY : construction.cc.o

construction.i: construction.cc.i
.PHONY : construction.i

# target to preprocess a source file
construction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/construction.cc.i
.PHONY : construction.cc.i

construction.s: construction.cc.s
.PHONY : construction.s

# target to generate assembly for a file
construction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/construction.cc.s
.PHONY : construction.cc.s

event.o: event.cc.o
.PHONY : event.o

# target to build an object file
event.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/event.cc.o
.PHONY : event.cc.o

event.i: event.cc.i
.PHONY : event.i

# target to preprocess a source file
event.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/event.cc.i
.PHONY : event.cc.i

event.s: event.cc.s
.PHONY : event.s

# target to generate assembly for a file
event.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/event.cc.s
.PHONY : event.cc.s

generator.o: generator.cc.o
.PHONY : generator.o

# target to build an object file
generator.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/generator.cc.o
.PHONY : generator.cc.o

generator.i: generator.cc.i
.PHONY : generator.i

# target to preprocess a source file
generator.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/generator.cc.i
.PHONY : generator.cc.i

generator.s: generator.cc.s
.PHONY : generator.s

# target to generate assembly for a file
generator.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/generator.cc.s
.PHONY : generator.cc.s

physics.o: physics.cc.o
.PHONY : physics.o

# target to build an object file
physics.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/physics.cc.o
.PHONY : physics.cc.o

physics.i: physics.cc.i
.PHONY : physics.i

# target to preprocess a source file
physics.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/physics.cc.i
.PHONY : physics.cc.i

physics.s: physics.cc.s
.PHONY : physics.s

# target to generate assembly for a file
physics.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/physics.cc.s
.PHONY : physics.cc.s

run.o: run.cc.o
.PHONY : run.o

# target to build an object file
run.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/run.cc.o
.PHONY : run.cc.o

run.i: run.cc.i
.PHONY : run.i

# target to preprocess a source file
run.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/run.cc.i
.PHONY : run.cc.i

run.s: run.cc.s
.PHONY : run.s

# target to generate assembly for a file
run.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/run.cc.s
.PHONY : run.cc.s

runAction.o: runAction.cc.o
.PHONY : runAction.o

# target to build an object file
runAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/runAction.cc.o
.PHONY : runAction.cc.o

runAction.i: runAction.cc.i
.PHONY : runAction.i

# target to preprocess a source file
runAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/runAction.cc.i
.PHONY : runAction.cc.i

runAction.s: runAction.cc.s
.PHONY : runAction.s

# target to generate assembly for a file
runAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/runAction.cc.s
.PHONY : runAction.cc.s

sim.o: sim.cc.o
.PHONY : sim.o

# target to build an object file
sim.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/sim.cc.o
.PHONY : sim.cc.o

sim.i: sim.cc.i
.PHONY : sim.i

# target to preprocess a source file
sim.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/sim.cc.i
.PHONY : sim.cc.i

sim.s: sim.cc.s
.PHONY : sim.s

# target to generate assembly for a file
sim.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/sim.cc.s
.PHONY : sim.cc.s

stepping.o: stepping.cc.o
.PHONY : stepping.o

# target to build an object file
stepping.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/stepping.cc.o
.PHONY : stepping.cc.o

stepping.i: stepping.cc.i
.PHONY : stepping.i

# target to preprocess a source file
stepping.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/stepping.cc.i
.PHONY : stepping.cc.i

stepping.s: stepping.cc.s
.PHONY : stepping.s

# target to generate assembly for a file
stepping.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/stepping.cc.s
.PHONY : stepping.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... simulation"
	@echo "... sim"
	@echo "... ElectromagneticPhysics.o"
	@echo "... ElectromagneticPhysics.i"
	@echo "... ElectromagneticPhysics.s"
	@echo "... GammaNuclearPhysics.o"
	@echo "... GammaNuclearPhysics.i"
	@echo "... GammaNuclearPhysics.s"
	@echo "... HadronElasticPhysicsHP.o"
	@echo "... HadronElasticPhysicsHP.i"
	@echo "... HadronElasticPhysicsHP.s"
	@echo "... MyG4StepLimiterPhysics.o"
	@echo "... MyG4StepLimiterPhysics.i"
	@echo "... MyG4StepLimiterPhysics.s"
	@echo "... PhysicsList.o"
	@echo "... PhysicsList.i"
	@echo "... PhysicsList.s"
	@echo "... RadioactiveDecayPhysics.o"
	@echo "... RadioactiveDecayPhysics.i"
	@echo "... RadioactiveDecayPhysics.s"
	@echo "... action.o"
	@echo "... action.i"
	@echo "... action.s"
	@echo "... construction.o"
	@echo "... construction.i"
	@echo "... construction.s"
	@echo "... event.o"
	@echo "... event.i"
	@echo "... event.s"
	@echo "... generator.o"
	@echo "... generator.i"
	@echo "... generator.s"
	@echo "... physics.o"
	@echo "... physics.i"
	@echo "... physics.s"
	@echo "... run.o"
	@echo "... run.i"
	@echo "... run.s"
	@echo "... runAction.o"
	@echo "... runAction.i"
	@echo "... runAction.s"
	@echo "... sim.o"
	@echo "... sim.i"
	@echo "... sim.s"
	@echo "... stepping.o"
	@echo "... stepping.i"
	@echo "... stepping.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

